### PR TITLE
fix update details WordPresscron jobs

### LINKED ISSUE #382: Check whether the script is working for updating details on the Spam Check stage
image

We need to re-check whether the cron is working

### PR DESCRIPTION
**Pull request by hugosolar**
## Fixes
Fixes #382 by @claudioruiz 

## Description
The script got stuck in a no-return point because it wasn't reading the correct date to compare the days. Everything is now fixed and:
- Users stuck with no reminder will have their first-reminder
- Users stuck with first reminders will now have their second reminder

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `master` branch of the repository.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

File: plugins/cc-global-network/cron/email-update-details-reminders.php [hunk 1]
```diff
@@ -49,10 +71,16 @@ function ccgn_email_update_details_reminders()
...
-        $days_in_state = ccgn_days_since_state_set($applicant_id, $now);
+        $state_date = new DateTime($status['date']);
+        $days_in_state = $state_date->diff($now)->days;
         if ($days_in_state > CCGN_CLOSE_UPDATE_DETAILS_AFTER_DAYS) {
             if ( ($status['state'] == 'second-reminder') && ($status['done']) ) {
                 ccgn_close_update_details_applicant($applicant_id);
+            } elseif ( $status['state'] == 'none' ) {
+                ccgn_update_details_set_first_reminder($applicant_id);
+            } elseif ( $status['state'] == 'first-reminder' ) {
+                echo "HEY I'M STUCK ON FIRST REMINDER \n";
```
Comment (TimidRobot) [inline plugins/cc-global-network/cron/email-update-details-reminders.php:82]: Should this `echo` be here (looks like a debug/testing statement)?

Comment (hugosolar) [reply plugins/cc-global-network/cron/email-update-details-reminders.php]: oops, yes... my bad. 🤦 
is fixed now
